--PIRHEADER
CREATE TABLE PIRHEADER(
	PHDNUMBER Varchar2(20) NOT NULL,
	PHDCLIENT Varchar2(20) NOT NULL,
	PHDDATE Varchar2(80) NULL,
	PHDPAYCCY Varchar2(6) NULL,
	PHDPRODUCT Varchar2(20) NULL,
	PIRMODE Varchar2(2) NULL,
	PHDBANKPRODUCT Varchar2(20) NULL,
	PHDACTIVATIONDATE Varchar2(80) NULL,
	MAKER_CODE Varchar2(20) NULL,
	MAKER_DATETIME Varchar2(80) NULL,
	RECORD_KEY_NO Varchar2(14) NULL,
	REQUEST_STATE Number(5) NULL,
	SELLER_CODE Varchar2(20) NULL,
	CHANNEL_CODE Varchar2(15) NULL,
	PHDPERIOD Varchar2(10) NULL,
	PHDDEBIT_PAY_CCY_AMNT Number(20, 4) NULL,
	PHDFXRATE Number(22, 9) NULL,
	PHDPRODUCTCAT Varchar2(20) NULL,
	PROCESS_DATE Varchar2(80) NULL,
	EFFECTIVE_DATE Varchar2(80) NULL,
	TXN_DATE Varchar2(80) NULL,
	CR_SELLER_LCY_AMNT Number(25, 4) NULL,
	DR_SELLER_LCY_AMNT Number(25, 4) NULL
);
commit;
------------------------------------------------------------------------------------------------
--PIRDETAIL
CREATE TABLE PIRDETAIL(
	PDTNUMBER Varchar2(20) NOT NULL,
	PDTBNKPRODUCT Varchar2(20) NULL,
	PDTACTDATE timestamp(7) NOT NULL,
	PDTACCBRANCH Varchar2(20) NULL,
	PDTINSTRUMENT Varchar2(10) NULL,
	PDTINSTAMOUNT Number(20, 2) NULL,
	DEBIT_CCY_AMNT Number(20, 4) NULL,
	RATETYPE Varchar2(15) NULL,
	PDTFXRATE Number(22, 9) NULL,
	PAYMENTCYY Varchar2(10) NULL,
	PDTREFERENCE Varchar2(80) NULL,
	PDTCHARGES Number(5) NULL,
	PAYMENTMETHOD Varchar2(15) NULL,
	REMIT_TXN_REF_NO Varchar2(20) NULL,
	PDTBENEFICIARY Varchar2(20) NULL,
	PARENT_RECORD_KEY_NO Varchar2(14) NULL,
	RECORD_KEY_NO Varchar2(14) NULL,
	REQUEST_STATE Number(3, 0) NULL,
	SELLER_CODE Varchar2(20) NULL,
	SMS_FLAG Varchar2(1) NULL,
	IVR_FLAG Varchar2(1) NULL,
	VALID_FLAG Varchar2(1) NULL,
	DR_CR_FLAG Varchar2(1) NOT NULL,
	INTER_SELLER_TXN Varchar2(1) NULL,
	DELIVERY_STATUS Varchar2(2) NULL,
	CLIENT_DEBIT_DATE timestamp(7) NULL,
	PDTACCTRFTYPE Varchar2(1) NULL,
	CF_PAYMENT_TYPE Varchar2(1) NULL,
	PROCESS_DATE timestamp(7) NULL,
	EFFECTIVE_DATE timestamp(7) NULL,
	TXN_DATE timestamp(7) NOT NULL,
	REVERSAL_FLAG Varchar2(2) NULL,
	INSTRUCTION_CODE Varchar2(255) NULL
);
commit;
------------------------------------------------------------------------------------------------
--LMS_MOVEMENT_TXN
CREATE TABLE LMS_MOVEMENT_TXN(
	MOVEMENT_ID Varchar2(20) NOT NULL,
	EXECUTION_ID Varchar2(50) NULL,
	MOVEMENT_TYPE Varchar2(1) NOT NULL,
	MOVEMENT_STATUS Varchar2(1) NULL,
	DEBIT_AMOUNT Number(20, 4) NOT NULL,
	CREDIT_AMOUNT Number(20, 4) NOT NULL,
	MOVEMENT_AMNT_BASE_CCY Number(20, 4) NULL,
	SELLER_CODE Varchar2(20) NOT NULL,
	ORIGINALNARRATION Varchar2(1000) NULL,
	AGREEMENT_RECKEY Varchar2(12) NULL,
	DEBIT_ACCOUNT_ID Number(19) NOT NULL,
	DEBIT_ACCOUNT_CCY Varchar2(10) NOT NULL,
	CREDIT_ACCOUNT_ID Number(19) NOT NULL,
	CREDIT_ACCOUNT_CCY Varchar2(10) NOT NULL,
	EXECUTION_DATE Timestamp(3) NOT NULL
);
commit;
------------------------------------------------------------------------------------------------
--SELLER_MST
CREATE TABLE SELLER_MST(
	SELLER_CODE Varchar2(20) NOT NULL,
	SELLER_DESCRIPTION Varchar2(40) NOT NULL,
	COUNTRY_CODE Varchar2(3) NOT NULL,
	CONTACT_PERSON Varchar2(40) NOT NULL,
	CONTACT_DESIGNATION Varchar2(30) NULL,
	ADDR_1 Varchar2(30) NULL,
	ADDR_2 Varchar2(30) NULL,
	ADDR_3 Varchar2(30) NULL,
	ADDR_4 Varchar2(30) NULL,
	ADDR_5 Varchar2(30) NULL,
	TEL_NMBR Varchar2(40) NULL,
	FAX_NMBR Varchar2(40) NULL,
	EMAIL_ID_NMBR Varchar2(255) NULL,
	RECORD_KEY_NMBR Varchar2(12) NOT NULL,
	AUDIT_NMBR Varchar2(12) NOT NULL,
	VALID_FLAG Varchar2(1) NOT NULL,
	OPERATION_FLAG Varchar2(1) NULL,
	CHECKER_ACTION Varchar2(1) NULL,
	PREV_AUDIT_NMBR Varchar2(12) NULL,
	VERSION Number(19) NULL,
	SELLER Varchar2(20) NULL,
	DISP_BANK_CODE Varchar2(10) NULL,
	TRIANG_CCY_CODE Varchar2(20) NULL,
	SYS_CONTROLLING_BRANCH_CODE Varchar2(10) NULL,
	CCY_CODE Varchar2(10) NULL,
	CLEARING_LOC_CODE Varchar2(10) NULL,
	LOCATION_TYPE Varchar2(10) NULL,
	STATE_CODE Varchar2(10) NULL,
	SI_TERMS_CONDITIONS Varchar2(4000) NULL,
	TIME_ZONE_CODE Varchar2(20) NULL,
	LOGO_ONOFF Varchar2(3) NULL,
	BUSINESS_NAME Varchar2(150) NULL,
	SELLER_SHORT_CODE Varchar2(3) NULL,
	TEMP_CLIENT_CODE Varchar2(10) NULL,
	BIC_CODE Varchar2(11) NULL,
	HOLIDAY_PROFILE_ID Varchar2(20) NULL
);
commit;
------------------------------------------------------------------------------------------------
--FX_RATES
CREATE TABLE FX_RATES(
	CCY_PAIR_CODE Varchar2(10) NOT NULL,
	CCY_CODE Varchar2(10) NOT NULL,
	DERIVED_CCY_CODE Varchar2(10) NOT NULL,
	UPDATE_TIME Timestamp(3) NOT NULL,
	FX_RATE Number(22, 9) NOT NULL,
	UPLOAD_NMBR Varchar2(20) NOT NULL,
	SELLER_CODE Varchar2(20) NOT NULL,
	BUY_FX_RATE Number(22, 9) NULL,
	SELL_FX_RATE Number(22, 2) NULL,
	SUSPENDED_BUY_RATE Varchar2(1) NULL,
	SUSPENDED_SELL_RATE Varchar2(1) NULL,
	SUSPENDED_MID_RATE Varchar2(1) NULL
);
commit;
------------------------------------------------------------------------------------------------
--PRODUCT_CATEGORY_MST
CREATE TABLE PRODUCT_CATEGORY_MST(
	PRODUCT_CATEGORY_CODE Varchar2(20) NULL,
	PRODUCT_CATEGORY_DESC Varchar2(100) NULL
);
commit;
------------------------------------------------------------------------------------------------
--PRODUCT_MST
CREATE TABLE PRODUCT_MST(
	PRODUCT_DESCRIPTION Nvarchar2(80) NOT NULL,
	PRODUCT_CODE Nvarchar2(40) NOT NULL
);
commit;
------------------------------------------------------------------------------------------------
--SUB_FACILITY_MST
CREATE TABLE SUB_FACILITY_MST(
	FACILITY_CODE Varchar2(10) NULL,
	SUB_FACILITY_CODE Varchar2(10) NOT NULL,
	SUB_FACILITY_DESC Varchar2(40) NULL,
	ENABLED_FLAG Varchar2(1) NULL,
	ASSET_LIABILITY_FLAG Varchar2(1) NULL
);
commit;
------------------------------------------------------------------------------------------------
--FACILITY_MST
CREATE TABLE FACILITY_MST(
	FACILITY_CODE Varchar2(10) NOT NULL,
	FACILITY_DESC Varchar2(40) NULL,
	ENABLED_FLAG Varchar2(1) NULL
);
commit;
------------------------------------------------------------------------------------------------
--PAYMENT_PACKAGE_MST
CREATE TABLE PAYMENT_PACKAGE_MST(
	PACKAGE_ID Varchar2(12) NOT NULL,
	PACKAGE_NAME Varchar2(40) NOT NULL
);
commit;
----------------------------------
CREATE TABLE CLIENT_SERVICE_SETUP_INC
(
ROW_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
CLIENT_ID VARCHAR2(12 Byte) NOT NULL,  
CLIENT_NAME VARCHAR2(150 Byte) NULL,   
CLIENT_TYPE VARCHAR2(1 Byte) DEFAULT 'M' NOT NULL,
CHECKER_STAMP DATE NULL,	
BRANDING_PKG_TYPE VARCHAR2(1 Byte) DEFAULT 'C' NULL,    
BR_ENABLE VARCHAR2(1 Byte) NULL,   
PAYMENT_ENABLE VARCHAR2(1 Byte) NULL,   
COLLECTION_ENABLE VARCHAR2(1 Byte) NULL,   
LMS_ENABLE VARCHAR2(1 Byte) NULL,   
FSC_ENABLE VARCHAR2(1 Byte) NULL,   
TRADE_ENABLE VARCHAR2(1 Byte) NULL,   
COORDINATOR_ENABLE VARCHAR2(1 Byte) NULL,
REMIT_ENABLE VARCHAR2(1 Byte) NULL, 
FORECAST_ENABLE VARCHAR2(1 Byte) NULL,   
POSITIVE_PAY_ENABLE VARCHAR2(1 Byte) NULL,   
CHECKS_ENABLE VARCHAR2(1 Byte) NULL,   
ADMIN_ENABLE VARCHAR2(1 Byte) NULL,   
SELLER_CODE VARCHAR2(20 Byte) NOT NULL,  
VALID_FLAG VARCHAR2(1 Byte) NOT NULL,  
RECORD_KEY_NO VARCHAR2(12 Byte) NOT NULL,  
BANK_REP_ENABLE VARCHAR2(1 Byte) NULL,   
ACTIVATION_DATE DATE NULL,    
DEPOSIT_ENABLE VARCHAR2(1 Byte) NULL,   
LIMIT_ENABLE VARCHAR2(1 Byte) NULL,   
LOANS_ENABLE VARCHAR2(1 Byte) NULL,   
THEME_PROFILE_ID VARCHAR2(12 Byte) NULL,   
PORTAL_ENABLE VARCHAR2(1 Byte) NULL,   
MOBILE_PAY_ENABLE VARCHAR2(1 Byte) DEFAULT 'N' NULL, 
MOBILE_BTR_ENABLE VARCHAR2(1 Byte) DEFAULT 'N' NULL, 
MOBILE_PP_ENABLE VARCHAR2(1 Byte) DEFAULT 'N' NULL, 
EXECUTION_ID VARCHAR2(50 Byte) NULL,   
MOBILE_ENABLE VARCHAR2(1 Byte) NULL,   
SUB_ACCOUNT_ENABLE VARCHAR2(1 Byte) DEFAULT 'N' NULL, 
TPFA_ENABLE VARCHAR2(1 Byte) DEFAULT 'N' NULL 
);

CREATE TABLE LMS_AGREEMENT_MST_INC
(
ROW_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
RECORD_KEY_NO VARCHAR2(12 BYTE) NOT NULL ENABLE, 
CHECKER_STAMP DATE NULL,
AGREEMENT_LIVE_DATE DATE, 
AGREEMENT_CURRENCY VARCHAR2(10 BYTE), 
CLIENT_CODE VARCHAR2(20 BYTE), 
VALID_FLAG VARCHAR2(1 BYTE), 
VALIDATED VARCHAR2(1 BYTE), 
SELLER_CODE VARCHAR2(20 BYTE)
);

CREATE TABLE LMS_NOTIONAL_AGREEMENT_MST_INC
(
ROW_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
RECORD_KEY_NO VARCHAR2(12 BYTE) NOT NULL ENABLE, 
CHECKER_STAMP DATE NULL,
VALID_FLAG VARCHAR2(1 BYTE),
SELLER_CODE VARCHAR2(20 BYTE), 	
CLIENT_ID VARCHAR2(12 BYTE) NOT NULL ENABLE, 
AGREEMENT_CODE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
STRUCTURE_TYPE VARCHAR2(3 BYTE) NOT NULL ENABLE, 
STRUCTURE_SUBTYPE NUMBER(*,0) NOT NULL ENABLE, 
SETTLEMENT_FREQUENCY_TYPE VARCHAR2(1 BYTE)
);


CREATE TABLE CPON_ACCOUNT_MST
(
ROW_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
ACCOUNT_ID NUMBER(10,0) NOT NULL ENABLE,   
CLIENT_ID VARCHAR2(12 BYTE) NOT NULL ENABLE,  
ACCT_NMBR VARCHAR2(100 BYTE) NOT NULL ENABLE,  
CCY_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,  
ACCT_TYPE VARCHAR2(10 BYTE),     
ACCT_SUB_TYPE VARCHAR2(10 BYTE),      
ACCT_USAGE_PAY VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
ACTIVE_FLAG VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
RECORD_KEY_NO VARCHAR2(12 BYTE) NOT NULL ENABLE,  
PARENT_RECORD_KEY VARCHAR2(12 BYTE) NOT NULL ENABLE,  
PAY_CREDIT_ACCT_FLAG VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,    
SYSTEM_BANK_FLAG VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,    
DR_LIMIT NUMBER(18,5),      
EXECUTION_ID VARCHAR2(50 BYTE)
); 

CREATE TABLE BTR_CURRENT_SUMMARY
(
ROW_ID  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
ACCOUNT_ID NUMBER(10),
RECORD_KEY_NO VARCHAR2(12),
SESSION_NMBR VARCHAR2(64),
CCY_CODE VARCHAR2(10),
SUMMARY_DATE DATE,
CLIENT_CODE  VARCHAR2(150),
CLIENT_DESCRIPTION VARCHAR2(160),
ACCOUNT_NMBR VARCHAR2(100),
ACCOUNT_NAME VARCHAR2(150),
BANK_CODE VARCHAR2(20),
BALANCE_TYPE VARCHAR2(1),
ACTIVE_FLAG  VARCHAR2(1),
SELLER_CODE  VARCHAR2(20),
ASSETS_LIABILITIES VARCHAR2(1),
SUB_FACILITY_CODE  VARCHAR2(10),
SUB_FACILITY_DESC  VARCHAR2(40),
SUMMARY_DATE_TRUNC DATE
);


CREATE TABLE BTR_CURRENT_SUMMARY_EXTN_1
(
ROW_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
ACCOUNT_ID   NUMBER(10),
SESSION_NMBR VARCHAR2(64),
ACCOUNT_NMBR VARCHAR2(100),
POSTING_DATE DATE,
ACTIVE_FLAG  VARCHAR2(1),
SELLER_CODE  VARCHAR2(20),
CLIENT_CODE  VARCHAR2(150),
CCY_CODE VARCHAR2(10),
SUB_FACILITY_CODE VARCHAR2(20),
TYPE65_AMNT  NUMBER(20,4),
TYPE68_AMNT  NUMBER(20,4),
TYPE74_AMNT  NUMBER(20,4),
TYPE78_AMNT  NUMBER(20,4),
TYPE83_AMNT  NUMBER(20,4),
TYPE92_AMNT  NUMBER(20,4),
POSTING_DATE_TRUNC DATE
);

CREATE TABLE BTR_HISTORY_SUMMARY
(
ROW_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
ACCOUNT_ID  NUMBER(10),
SESSION_NMBR VARCHAR2(64),
SUMMARY_DATE DATE,
RECORD_KEY_NO VARCHAR2(12),
CLIENT_CODE   VARCHAR2(150),
CLIENT_DESCRIPTION VARCHAR2(160),
ACCOUNT_NMBR VARCHAR2(100),
ACCOUNT_NAME VARCHAR2(150),
CCY_CODE VARCHAR2(10),
CCY_DESCRIPTION  VARCHAR2(40),
ACTIVE_FLAG  VARCHAR2(1),
SELLER_CODE  VARCHAR2(20),
SUB_FACILITY_CODE  VARCHAR2(10),
SUB_FACILITY_DESC  VARCHAR2(40),
SUMMARY_DATE_TRUNC DATE,
BANK_CODE VARCHAR2(20)
);

CREATE TABLE BTR_HISTORY_SUMMARY_EXTN_1
(
ROW_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
ACCOUNT_ID  NUMBER(10),
SESSION_NMBR VARCHAR2(64),
SEQUENCE_NMBR NUMBER(10),
ACCOUNT_NMBR VARCHAR2(100),
SUB_FACILITY_CODE VARCHAR2(20),
ACTIVE_FLAG VARCHAR2(1),
SELLER_CODE VARCHAR2(20),
CLIENT_CODE VARCHAR2(150),
CCY_CODE VARCHAR2(10),
POSTING_DATE DATE,
TYPE65_AMNT  NUMBER(20,4),
TYPE68_AMNT  NUMBER(20,4),
TYPE74_AMNT  NUMBER(20,4),
TYPE78_AMNT  NUMBER(20,4),
TYPE83_AMNT  NUMBER(20,4),
TYPE92_AMNT  NUMBER(20,4),
POSTING_DATE_TRUNC DATE   
);

commit;


exit;